name: Crave Builder
on:
  workflow_dispatch:
    inputs:
      CLEAD_BUILD:
        description: 'Build with a clean workspace?'
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest
    outputs:
      MESSAGE_ID: ${{ steps.msg_1.outputs.MESSAGE_ID }}

    steps:
    - name: Check-out
      uses: actions/checkout@v4

    - name: Check Credentials
      run: |
        if [[ -z "${{ secrets.CRAVE_TOKEN }}" || -z "${{ secrets.CRAVE_USERNAME }}" ]]; then
          echo "Crave Credentials Not Configured! Exiting..."
          exit 1
        fi
        bash scripts/env-checker.sh

    - name: Make scripts executable
      run: chmod +x scripts/telegram.sh

    - name: Run Telegram Script
      id: msg_1
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "
        ${{ github.actor }} has triggered a build.
        " >> content.txt
        ./scripts/telegram.sh content.txt

    - name: Set Project Variables
      id: vars
      run: |
        echo "DEVICE=creek" >> $GITHUB_OUTPUT
        echo "BUILD_TYPE=user" >> $GITHUB_OUTPUT

    - name: Set Build Variables
      id: build_vars
      run: |
        echo "CLEAD_BUILD=${{ github.event.inputs.CLEAD_BUILD }}" >> $GITHUB_OUTPUT

    - name: Telegram Build Start Message
      id: msg_2
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "
        Build started for ${{ github.actor }}.
        Device: ${{ steps.vars.outputs.DEVICE }}
        Build Type: ${{ steps.vars.outputs.BUILD_TYPE }}
        Clean Build: ${{ steps.build_vars.outputs.CLEAD_BUILD }}
        " >> content.txt
        ./scripts/telegram.sh EDIT ${{outputs.MESSAGGE_ID}} content.txt

  build:
    name: build
    needs: prepare
    runs-on: self-hosted
    concurrency:
      group: ${{ github.repository_owner }}
    steps:

    - name: Echo
      run: echo 'Hello from crave!'
