name: Crave Builder
on:
  workflow_dispatch:
    inputs:
      CLEAD_BUILD:
        description: 'Build with a clean workspace?'
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v4

    - name: Check Credentials
      run: |
        if [[ -z "${{ secrets.CRAVE_TOKEN }}" || -z "${{ secrets.CRAVE_USERNAME }}" ]]; then
          echo "Crave Credentials Not Configured! Exiting..."
          exit 1
        fi
        bash scripts/env-checker.sh

    - name: Make scripts executable
      run: chmod +x scripts/telegram.sh

    - name: Run Telegram Script
      id: msg_1
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "
        hello, ${{ github.actor }} has triggered a build for the repository ${{ github.repository }}.
        " >> content.txt
        ./scripts/telegram.sh content.txt

  build:
    name: build
    needs: prepare
    runs-on: self-hosted
    concurrency:
      group: ${{ github.repository_owner }}
    steps:

    - name: Echo
      run: echo 'Hello from crave!'
